### ISSUE TITLE
Add visual feedback on answer submission

### ISSUE THREAD

**Issue by NiloCK** [NiloCK/vue-skuilder#44]
Red/green flashes a la mrkennedy.ca/countby seem reasonable.

Some prelim work:

``` css
correct-true {
  animation: greenFade 500ms ease-out;
}
correct-false {
  animation: purpleFade 750ms ease-out;
}

@keyframes greenFade {
  0% {
    background-color: green !important;
  }
  100% {
    background: white;
  }
}
@keyframes purpleFade {
  0% {
    background: purple;
  }
  100% {
    background: white;
  }
}
```

``` js
if (r.isCorrect) {
        this.loadRandomCard();
        cardDiv.classList.add('correct-true');
      } else {
        cardDiv.classList.add('correct-false');
      }

      setTimeout(() => {
        cardDiv.classList.remove('correct-true', 'correct-false');
      }, 750);
```
